config/routes.rb
Rails.application.routes.draw do

  resources :images
  resources :charges
  resources :orders do
    member do
      get 'success'
    end
  end
  root to: "home#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
    validates :address_line_1, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :zip_code, presence: true 
    
    STATUS_PAID = "paid"
    
    def confirm_payment
      update_attribute(:payment_status, STATUS_PAID)
      send_confirmation_emails
      paid?
    end

    def paid?
      payment_status == STATUS_PAID
    end

    private

    def send_confirmation_emails
      jason_pic = Instagram.media_item(instagram_id).images.standard_resolution.url

      if paid?
        UserMailer.order_confirmation(self).deliver
        OwnerMailer.new_order_alert(self, jason_pic).deliver
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def index
  end

  def new
    @order = Order.find params[:id]
    session[:id] = @order.id
  end 

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd',
    )

    order = Order.find(session[:id])
    if order.confirm_payment
      reset_session
    end
    redirect_to success_order_path(order)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    #id = "25e9ba1460bf47bb93567ee703dbdf4f"
    #token = "4433201.25e9ba1.9c84ed99f4c84951a476b08855236735"
    #user_id = "4433201"
    id = INSTAGRAM_CLIENT_ID
    token = INSTAGRAM_TOKEN
    user_id = INSTAGRAM_UID
    @photos = Instagram.user_recent_media(user_id, {client_id: id, access_token: token,count: 28,})
    #@photos_next = Instagram.user_recent_media(user_id, {client_id: id, access_token: token, count: 12, max_id: '452467253150086099'})
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    #images = Instagram.user_recent_media(INSTAGRAM_UID, {client_id: INSTAGRAM_CLIENT_ID, count: 1, access_token: INSTAGRAM_TOKEN})
    images = Instagram.user_recent_media(INSTAGRAM_UID, 
      {client_id: INSTAGRAM_CLIENT_ID, 
        count: 12, 
        access_token: INSTAGRAM_TOKEN, 
        max_id: params['max_id']})
    #binding.pry
    render json: images
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def success
    @order = Order.find params[:id]
  end

  def new
    @order = Order.new 
    @order.instagram_id = params[:instagram_id]

    Instagram.configure do |c|
      c.access_token = INSTAGRAM_TOKEN
      c.client_id = INSTAGRAM_CLIENT_ID
    end
    
    @jason_pic = Instagram.media_item(@order.instagram_id).images.standard_resolution.url
  end

  def create
    #binding.pry
    @order = Order.create params[:order].permit :payment_status, :instagram_id, :photo_url, :first_name, :last_name, :email, :address_line_1, :address_line_2, :city, :state, :zip_code
    redirect_to new_charge_path(id: @order.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.slim
h2
  | Thanks, you paid $5.00 !

app/views/charges/new.html.slim
= form_tag charges_path do
  article
    label class = "amount"
      span
        | Amount: $5.00

  = javascript_include_tag "https://checkout.stripe.com/checkout.js", class: "stripe-button", data: {key: PUBLISHABLE_KEY, amount: 500, order_id: @order.id}

  //script src= "https://checkout.stripe.com/checkout.js" class="stripe-button"
         //data-key= "#{PUBLISHABLE_KEY}" 
         //data-order-id= "#{@order.id}"
         //data-description="A month's subscription"
         //data-amount="500"

app/views/home/index.html.slim
.title
  h1
    | somerset 
    span GREENE

  .navigation
    ul
      li = link_to "contact", "mailto:somersetgreene@gmail.com", target: "blank"
      li = link_to "instagram", "http://instagram.com/somersetgreene", target: "blank"
      //li = link_to "print info", class: "print_info"
.images
  - @photos.each do |show|
    .thumbnail
      = image_tag show.images.low_resolution.url, 'data-image_id'=> show.id.split("_")[0]
      = link_to 'buy 12x12 print', new_order_path(instagram_id: show.id), class: "purchase"

.pagination
  = link_to 'view more images', nil, id: "load_more_images", remote: true, class: "view_more"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Somerset Greene</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/charges.html.slim
= yield

app/views/orders/create.html.slim
h1
  = "Thanks for your order #{@order.first_name}"

app/views/orders/new.html.slim
.shipping_header
    h1
        | Shipping Information
.image
    = image_tag @jason_pic
    p
        = "image-id: #{@order.instagram_id}"

.form
    ul
      = form_for @order, url: {action: "create"} do |f|

        li
            //= f.label :instagram_image_number
            = f.hidden_field :instagram_id, readonly: true
        li
            = f.label :first_name, 'First Name'
            = f.text_field :first_name, required: true, class: "text_field"
        li        
            = f.label :last_name, 'Last Name'
            = f.text_field :last_name, required: true, class: "text_field"
        li
            = f.label :email, 'Email Address'
            = f.text_field :email, required: true, class: "text_field"
        li    
            = f.label :address_line_1, 'Address Line 1'
            = f.text_field :address_line_1, required: true, class: "text_field"
        li
            = f.label :address_line_2, 'Address Line 2'
            = f.text_field :address_line_2, class: "text_field"
        li
            = f.label :city, 'City'
            = f.text_field :city, required: true, class: "text_field"
        li
            = f.label :state, 'State'
            = f.text_field :state, required: true, class: "text_field"
        li
            = f.label :zip_code, 'Zip Code'
            = f.text_field :zip_code, required: true, class: "text_field"
        li
            = f.submit

        p
            | click 'create order' to move on to checkout!

app/views/orders/success.html.slim
.message
  h1
    = "Thank you for your order #{@order.first_name}!"
  p
    | you will receive a confirmation email shortly